### ISSUE TITLE
Whitespace collapse needs a "conservative" (HTML strict) option

### ISSUE THREAD

**Issue by stevenvachon** [vbenjs/vite-plugin-html#168]
The current implementation has forced me to add pseudo-elements containing whitespace in situations like this:

```html
<h3>Title</h3>
<ul>
  <li>Item</li>
</ul>
```

...minifying to:

```html
<h3>Title</h3><ul><li>Item</li></ul>
```

...which, when I have:

```css
h3, ul, li {
  display: inline;
}

h3::after {
  content: ':';
}
```

...renders as:

```
Title:Item
```

..._instead of_:

```
Title: Item
```

...which is how spec-compliant HTML collapses whitespace. Obviously, my fix is:

```css
h3::after {
  content: ': ';
}
```

~~...but this isn't noticed in dev because of #78 and had to be corrected after a deploy.~~

Regardless, this plugin should optionally use [normalize-html-whitespace](https://npmjs.com/normalize-html-whitespace).
